AWSTemplateFormatVersion: 2010-09-09
Description: Primeiro Template escrito à mão
Resources:

  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-00169914e6299b8e0
      InstanceType: t2.micro
      Tags:
        - 
          Key: Name
          Value: Formation Labs
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup

  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Web Acess
      SecurityGroupIngress:
        - 
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
      Tags:
          -
            Key: Name
            Value: Web Server Security Group